services:
  postgres:
    image: postgres:18
    container_name: crud-postgres
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - crud_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d crud"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: .
    container_name: crud-spring-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crud
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      API_SECURITY_TOKEN_SECRET: ${API_KEY}
    ports:
      - "8080:8080"
volumes:
  crud_pgdata: