spring.application.name=crud
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
api.security.token.secret=cIAI2XgOhwqZPJBjvBb4tOGknbtNZYbxvjQc7PxjPcYxWt1macVYIezqZhUY7RZ8S26fVCNnP0F6b86m6U5cQ3
logging.level.org.springframework.security=DEBUG
